version: '2'

services:
    craft:
      build: .
      container_name: craft
      ports:
        - 80:80
      volumes:
        - /var/log
        - ./local_share:/local_share
        - ./craft:/usr/share/nginx
      links:
        - mysql
        - memcached
      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # MEMCACHED is linked
        MEMCACHED_HOST: memcached

        # DB is linked
        DB_DRIVER: mysql
        DB_SERVER: mysql
        DB_DATABASE: craft3beta
        DB_PASSWORD: secret
        DB_SCHEMA: public
        DB_PORT: '3306'
        DB_USER: craft3beta
        LANG: C.UTF-8
        MEMCACHED_HOST: memcached

    mysql:
      container_name: mysql
      image: mysql:5.7
      restart: always
      volumes:
        - /var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: craft3beta
          MYSQL_USER: craft3beta
          MYSQL_PASSWORD: secret

    phpmyadmin:
      container_name: phpmyadmin
      links:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: dev

    memcached:
      image: memcached:1.5.2
